FROM node:24.12.0-alpine3.23

RUN apk add bash
RUN apk add curl
RUN apk add vim

RUN npm install -g npm@11.7.0 typescript@5.9.3 pnpm@10.26.2

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

RUN pnpm run db:migrate

EXPOSE 5000

CMD ["bash","-c","pnpm run dev"]