services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: faizahmed546/express-pet:latest
    container_name: backend-prod
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: YOUR_PRODUCT_DATABASE_URL
    restart: always

  
